services:
  watchtower:
    image: containrrr/watchtower
    env_file:
      - ./watchtower.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --debug --http-api-update --http-api-periodic-polls
    ports:
      - 54321:8080
  web:
    container_name: simple_django_web
    image: zxdmimfort/simple_django:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "8000:80"
    volumes:
      - ./nc/media:/app/media
    env_file:
      - ./nc/.env.dev
    depends_on:
      - db
      - watchtower
      - redis
  db:
    container_name: simple_django_db
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
      - DATABASE=postgres
  redis:
    container_name: simple_django_redis
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  postgres_data:
