services:
  watchtower:
    image: containrrr/watchtower
    env_file:
      - ./watchtower.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --debug --http-api-update --http-api-periodic-polls
    ports:
      - 54321:8080
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/dev/Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./static/:/app/static/
      - ./backend/media/:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - web
  web:
    container_name: simple_django_web
    restart: always
    image: zxdmimfort/simple_django:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./static/:/app/static
      - ./backend/media/:/app/media/
    depends_on:
      - db
      - watchtower
      - redis
  db:
    container_name: simple_django_db
    restart: always
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  redis:
    container_name: simple_django_redis
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  postgres_data:
