services:
  web:
    container_name: simple_django_web
    build:
      context: nc
      target: builder
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "8000:80"
    volumes:
      - ./nc/:/app/
    env_file:
      - ./nc/.env.dev
    depends_on:
      - db
      - redis
  db:
    container_name: simple_django_db
    image: postgres:15
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
      - DATABASE=postgres
  redis:
    container_name: simple_django_redis
    image: redis:latest
volumes:
  postgres_data: