# Generated by Django 4.2.7 on 2023-11-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0005_category_worker_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="workers.category"
            ),
        ),
    ]
