# Generated by Django 4.2.7 on 2023-12-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_tagpost_alter_worker_cat_worker_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Husband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='workers', to='workers.tagpost'),
        ),
        migrations.AddField(
            model_name='worker',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.husband'),
        ),
    ]
