# Generated by Django 4.2.7 on 2023-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0011_uploadfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d",
                verbose_name="Фото",
            ),
        ),
    ]
